// BP 퀴즈 카드 데이터
// 출처: Data Management SPICE V2.0 표준 원문 — MGD.2/MGD.3/DOP.1/DOP.2 Process Purpose,
// Base Practices, Rating Rules. 회사/고객 관련 정보는 포함하지 않음.
//
// 필드:
//   id    카드 식별자
//   proc  프로세스 이름 (문제에 표시)
//   bp    BP 번호 또는 "Purpose" (문제에 표시)
//   short 정답 — 한 줄 의도
//   why   (선택) 자문자답용 질문 — Rating Rule에 근거가 있는 카드만 포함
//   bg    true면 배경 카드(MGD.1) — 기본 퀴즈 대상에서 제외
const DECK = [
  // MGD.2
  { id: "M2-P", proc: "MGD.2", bp: "Purpose",
    short: "이해관계자 니즈·요구사항을 도출·관리해 데이터 내용과 품질의 일관성 지원" },
  { id: "M2-1", proc: "MGD.2", bp: "BP1",
    short: "데이터가 실제로 어떻게 쓰이는지 시나리오로 정리 (Specify operational concepts and scenarios)" },
  { id: "M2-2", proc: "MGD.2", bp: "BP2",
    short: "이해관계자가 원하는 것을 요구사항으로 끌어냄 (Elicit stakeholder requirements)" },
  { id: "M2-3", proc: "MGD.2", bp: "BP3",
    short: "데이터 관리·품질 요구사항으로 구체화 (Derive requirements)" },
  { id: "M2-4", proc: "MGD.2", bp: "BP4",
    short: "기준을 정해 요구사항이 올바른지 검증 (Analyze and validate requirements)" },
  { id: "M2-5", proc: "MGD.2", bp: "BP5",
    short: "상위·하위 요구사항 연결, 모순 없음 확인 (Ensure consistency and establish traceability)",
    why: "왜 이 BP는 항상 소통(BP6) 바로 앞에 오는가?" },
  { id: "M2-6", proc: "MGD.2", bp: "BP6",
    short: "합의된 요구사항과 변경을 관련자에게 알림 (Communicate requirements)",
    why: "MGD.2와 MGD.3 둘 다 왜 마지막이 \"연결 → 소통\"으로 끝나는가?" },
  // MGD.3
  { id: "M3-P", proc: "MGD.3", bp: "Purpose",
    short: "요구사항에 기반해 데이터 관리 시스템(DMS)을 명세하고 데이터 흐름을 설계" },
  { id: "M3-1", proc: "MGD.3", bp: "BP1",
    short: "어떤 기술로 DMS를 만들지 정함 (Specify technical concept)",
    why: "기술개념이 거버넌스 제약을 다루지도 않고 별도 증거도 참조하지 않으면 이 BP는 어떻게 되는가? (MGD.3.RL.1 — 둘 다 해당해야 downrate, 증거 참조만 있어도 예외)" },
  { id: "M3-2", proc: "MGD.3", bp: "BP2",
    short: "데이터가 어디서 어디로 흐르는지 정함 (Specify data flows)" },
  { id: "M3-3", proc: "MGD.3", bp: "BP3",
    short: "데이터가 어디서 오는지(출처) 정함 (Specify sources of data)" },
  { id: "M3-4", proc: "MGD.3", bp: "BP4",
    short: "출처 중 가장 믿을 수 있는 원본을 표시 (Define authoritative sources of data)" },
  { id: "M3-5", proc: "MGD.3", bp: "BP5",
    short: "책임·소유권이 바뀌는 경계 지점을 정함 (Specify demarcation points)" },
  { id: "M3-6", proc: "MGD.3", bp: "BP6",
    short: "품질 활동·기준·규칙·임계값을 정함 (Specify data quality)" },
  { id: "M3-7", proc: "MGD.3", bp: "BP7",
    short: "데이터 구조·필드·관계·제약을 정함 (Specify conceptual schema)" },
  { id: "M3-8", proc: "MGD.3", bp: "BP8",
    short: "요구사항 ↔ 기술개념 ↔ 데이터 흐름 연결 (Ensure consistency and establish traceability)",
    why: "왜 이 BP는 항상 소통(BP9) 바로 앞에 오는가?" },
  { id: "M3-9", proc: "MGD.3", bp: "BP9",
    short: "결과를 공유하고 의도된 목적과 맞춤 (Communicate and align results)",
    why: "MGD.2와 MGD.3 둘 다 왜 마지막이 \"연결 → 소통\"으로 끝나는가?" },
  // DOP.1
  { id: "D1-P", proc: "DOP.1", bp: "Purpose",
    short: "데이터와 DMS를 운영 전환에 대비해 준비 (DMS/흐름/품질/거버넌스 준비 상태 보장)" },
  { id: "D1-1", proc: "DOP.1", bp: "BP1",
    short: "통합·배포 방법을 정함: 단계, 진입/종료 기준, 책임 인계 (Specify data integration and deployment approach)",
    why: "왜 이 BP 점수가 DOP.1의 나머지 BP2~6 전체의 상한이 되는가? (DOP.1.RL.1)" },
  { id: "D1-2", proc: "DOP.1", bp: "BP2",
    short: "통합·배포 때 쓸 품질 활동·기준을 고름 (Select data quality activities and criteria)",
    why: "MGD.3.BP6(데이터 품질 명세)이 downrate되면 이 BP는 어떻게 되는가? (DOP.1.RL.2)" },
  { id: "D1-3", proc: "DOP.1", bp: "BP3",
    short: "실제로 통합하고 검증함 (Integrate, verify, and validate data)" },
  { id: "D1-4", proc: "DOP.1", bp: "BP4",
    short: "고른 품질 기준을 적용하고 결과를 기록·소통 (Apply data quality activities and criteria)",
    why: "MGD.3.BP6(데이터 품질 명세)이 downrate되면 이 BP는 어떻게 되는가? (DOP.1.RL.2)" },
  { id: "D1-5", proc: "DOP.1", bp: "BP5",
    short: "운영할 사람들을 준비시킴, 교육 등 (Prepare for data operations)" },
  { id: "D1-6", proc: "DOP.1", bp: "BP6",
    short: "준비 상태를 확인해 배포하고 결과를 기록 (Manage deployment)" },
  // DOP.2
  { id: "D2-P", proc: "DOP.2", bp: "Purpose",
    short: "운영 중 DMS 성능·데이터 거버넌스 이행·데이터 품질 임계값 달성을 모니터링해 의도된 목적 달성" },
  { id: "D2-1", proc: "DOP.2", bp: "BP1",
    short: "운영 중 무엇을 어떻게 볼지 방법을 정함 (Specify data operations and optimization approach)",
    why: "이 BP가 downrate되면 무엇의 상한이 되는가? (DOP.2.RL.1 — 원문 표기 그대로는 \"DOP.1.BP2-6\"이 상한 대상, 오탈자 가능성 있으나 원문 그대로 인용)" },
  { id: "D2-2", proc: "DOP.2", bp: "BP2",
    short: "DMS 성능 모니터링, Purpose ① (Monitor data management system operations)" },
  { id: "D2-3", proc: "DOP.2", bp: "BP3",
    short: "고른 품질 활동을 운영 중 수행 (Perform selected data quality activities)" },
  { id: "D2-4", proc: "DOP.2", bp: "BP4",
    short: "품질을 임계값과 비교해 모니터링, Purpose ③ (Monitor data quality)" },
  { id: "D2-5", proc: "DOP.2", bp: "BP5",
    short: "거버넌스 준수 모니터링, Purpose ② (Monitor data governance)" },
  { id: "D2-6", proc: "DOP.2", bp: "BP6",
    short: "운영이 원래 목적에 맞는지 확인 (Ensure intended purpose)",
    why: "MGD.3.BP6(데이터 품질 명세)이 downrate되면 이 BP는 어떻게 되는가? (DOP.2.RL.3)" },
  // MGD.1 — 배경 (기본 퀴즈 제외)
  { id: "M1-P", proc: "MGD.1", bp: "Purpose", bg: true,
    short: "범위 식별·이해관계자 관리·비즈니스 케이스/용어집 정렬" },
  { id: "M1-1", proc: "MGD.1", bp: "BP1", bg: true,
    short: "범위·데이터 거버넌스 제약·데이터 유형 식별 (Identify scope, data governance, and data types)" },
  { id: "M1-2", proc: "MGD.1", bp: "BP2", bg: true,
    short: "이해관계자 식별·관리, 잠재적 갈등 포함 (Identify and manage stakeholders)" },
  { id: "M1-3", proc: "MGD.1", bp: "BP3", bg: true,
    short: "비즈니스 케이스 정렬: 편익/비용/리스크 (Specify and align business case)" },
  { id: "M1-4", proc: "MGD.1", bp: "BP4", bg: true,
    short: "용어집 명세·최신화 (Specify and align business glossary)" },
];
